version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

  my-backend:
    image: ghcr.io/eseniyalvanovna/my-backend:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__PostgresDB=Host=db;Database=postgres;Username=postgres;Password=password
    depends_on:
      - db
    ports:
      - "9032:9032"
    networks:
      - my-network

  my-frontend:
    image: ghcr.io/eseniyalvanovna/my-backend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - my-backend
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge
